[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
petgraph = "0.6.5"
itertools = "0.13.0"
num-traits = "0.2.19"
log = "0.4.22"
log4rs = "1.3.0"
either = "1.13.0"
rustc-hash = "2.0.0"
rayon = "1.10.0"

[dev-dependencies]
rand_chacha = "0.3.1"
env_logger = "0.11.5"

[features]
trace = []
time = []
